### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by rtyley** [guardian/ophan-geoip-db-refresher#7]
The GeoIp file has grown _slightly_ larger (from 134368384 to 134801401 bytes) - and now we're seeing consistent OutOfMemoryErrors?!

Memory usage as reported at the end of an unsuccessful run with 512MB:

> REPORT RequestId: 8f4b33f4-8913-4095-9bfa-3b1f64fd1e6a	Duration: 38466.58 ms	Billed Duration: 38467 ms	Memory Size: 512 MB	Max Memory Used: 395 MB

We increased memory size to 1024MB, and the function ran successfully:

> REPORT RequestId: b4a76e3b-581d-4296-a613-0ca50ec92e2f	Duration: 19931.72 ms	Billed Duration: 19932 ms	Memory Size: 1024 MB	Max Memory Used: 750 MB	Init Duration: 416.56 ms

...this would indicate, for the time being at least, we need a minimum of 750 MB for this lambda. It's surprisingly inefficent given the streaming code involved though 😢 

```
Java heap space: java.lang.OutOfMemoryError
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Unknown Source)
	at java.base/java.io.ByteArrayOutputStream.grow(Unknown Source)
	at java.base/java.io.ByteArrayOutputStream.ensureCapacity(Unknown Source)
	at java.base/java.io.ByteArrayOutputStream.write(Unknown Source)
	at java.base/sun.net.www.http.PosterOutputStream.write(Unknown Source)
	at software.amazon.awssdk.utils.IoUtils.copy(IoUtils.java:113)
	at software.amazon.awssdk.utils.IoUtils.copy(IoUtils.java:99)
	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$RequestCallable.lambda$null$0(UrlConnectionHttpClient.java:208)
	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$RequestCallable$$Lambda$437/0x000000084036d840.get(Unknown Source)
	at software.amazon.awssdk.utils.FunctionalUtils.lambda$safeSupplier$4(FunctionalUtils.java:108)
	at software.amazon.awssdk.utils.FunctionalUtils$$Lambda$77/0x000000084016e840.get(Unknown Source)
	at software.amazon.awssdk.utils.FunctionalUtils.invokeSafely(FunctionalUtils.java:136)
	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$RequestCallable.lambda$call$1(UrlConnectionHttpClient.java:208)
	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$RequestCallable$$Lambda$436/0x000000084036e440.accept(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$RequestCallable.call(UrlConnectionHttpClient.java:207)
	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$RequestCallable.call(UrlConnectionHttpClient.java:193)
	at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:64)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.executeHttpRequest(MakeHttpRequestStage.java:76)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:55)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:64)
```

**Comment by rtyley** [comment]
It seems that the `sun.net.www.protocol.http.HttpURLConnection` class that underlies the `java.net.HttpURLConnection` class used by `software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient` will only stream it's output if it is in `streaming()` mode - otherwise it buffers the entire file to memory in a `sun.net.www.http.PosterOutputStream` (essentially a `ByteArrayOutputStream`) before sending it:

https://github.com/openjdk/jdk/blob/da75f3c4ad5bdf25167a3ed80e51f567ab3dbd01/src/java.base/share/classes/sun/net/www/protocol/http/HttpURLConnection.java#L1373-L1394

...in order for [`streaming()`](https://github.com/openjdk/jdk/blob/da75f3c4ad5bdf25167a3ed80e51f567ab3dbd01/src/java.base/share/classes/sun/net/www/protocol/http/HttpURLConnection.java#L1411-L1414) mode to be true, either [`setFixedLengthStreamingMode(contentLength)`](https://github.com/openjdk/jdk/blob/da75f3c4ad5bdf25167a3ed80e51f567ab3dbd01/src/java.base/share/classes/java/net/HttpURLConnection.java#L245-L257) or [`setChunkedStreamingMode(chunklen)`](https://github.com/openjdk/jdk/blob/da75f3c4ad5bdf25167a3ed80e51f567ab3dbd01/src/java.base/share/classes/java/net/HttpURLConnection.java#L290-L298) must be called. Unfortunately, AWS's`UrlConnectionHttpClient.createAndConfigureConnection()` does not do this:

https://github.com/aws/aws-sdk-java-v2/blob/3b6ab4834c8fd641f2b1811852605c5aaf2d3871/http-clients/url-connection-client/src/main/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClient.java#L129-L144

...despite the stream length being known in advance, and set appropriately by the `ophan-geoip-db-refresher` code:

https://github.com/guardian/ophan-geoip-db-refresher/blob/810bd71d28b94fa90244d0f218360c17cbb92a35/src/main/scala/ophan/geoip/db/refresher/MaxmindDatabaseEdition.scala#L14

`createAndConfigureConnection()` _does_ pass through the correct HTTP `Content-Length` header, with a value of `134801401` (note that does exactly match the size we're trying to upload!), so it would be probably be entirely possible for it to also call `setFixedLengthStreamingMode(contentLength)` if the `Content-Length` header is present.
